name: PC Virtual Gamer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build APK Gamer
    runs-on: ubuntu-latest

    steps:
      - name: 🎮 Baixar projeto
        uses: actions/checkout@v4

      - name: ☕ Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: ⚙️ Configurar Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: 🔧 Dar permissão ao Gradle
        run: chmod +x gradlew

      - name: 🚀 Compilar PC Virtual
        run: ./gradlew assembleDebug

      - name: 📦 Publicar APK
        uses: actions/upload-artifact@v4
        with:
          name: PC-Virtual-Gamer-APK
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: 🏁 Build concluído
        run: echo "PC Virtual Gamer compilado com sucesso!"

      - name: 🔥 Status
        run: echo "APK pronto para download nos Artifacts!"
